config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'mains#index'

  get '/list_organizers', to: 'mains#all_organizers', as: 'all_organizers'
  get '/about_organizer/:id', to: 'mains#about_organizer', as: 'about_organizer'

  get '/all_future_events', to: 'mains#all_future_events', as: 'all_future_events'
  get '/about_event/:id', to: 'mains#about_event', as: 'about_event'
  get '/show_past_events', to: 'mains#show_past_events', as: 'show_past_events'

  get '/about_event_ics_file/:id', to: 'mains#about_event_ics_file', as: 'about_event_ics_file'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organizer
  belongs_to :region

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/organizer.rb
class Organizer < ApplicationRecord
  has_many :event
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

  def index
  end

  def all_organizers
    @all_organizers = Organizer.all
  end

  def about_organizer
    @about_organizer = Organizer.find(params[:id])
    all_events_organizer = Event.where(organizer_id: @about_organizer)
    @sort_past_events = []
    all_events_organizer.each do |event|
      if event.date_and_time < Time.now
        @sort_past_events.push event
      else next
      end
    end
  end

  def about_event
    @about_event = Event.find(params[:id])
    @about_event_organizer_id = @about_event.organizer_id
  end

  def all_future_events
    array_future_events = []
    all_events = Event.all
    all_events.each do |event|
      if event.date_and_time > Time.now
        array_future_events.push event
      else next
      end
    end
    @all_future_events = array_future_events.sort_by { |e| e[:date_and_time] }.reverse.paginate(page: params[:page], per_page: 1)
  end

  def show_past_events
    array_past_events = []
    all_events = Event.all
    all_events.each do |event|
      if event.date_and_time < Time.now
        array_past_events.push event
      else next
      end
    end
    @past_events = array_past_events.paginate(page: params[:page], per_page: 1)
  end

  def about_event_ics_file
    @event = Event.find(params[:name])
    respond_to do |format|
      format.ics do
        cal = Icalendar::Calendar.new
        cal.x_wr_calname = 'Awesome Rails Calendar'
        cal.event do |e|
          e.dtstart     = @event.date_and_time
          e.dtend       = @event.date_and_time
          e.summary     = @event.name
          e.description = @event.description
          e.location = @event.location
        end
        cal.publish
        render plain: cal.to_ical
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="navbar-nav navbar-left">
        <%= link_to 'Мероприятия', all_future_events_path, class: 'btn btn-default navbar-btn' %>
        <%= link_to 'Список организаторов', all_organizers_path, class: 'btn btn-default navbar-btn' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ITEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar.html.erb' %>
    <%= yield %>
  </body>
</html>

app/views/mains/about_event.html.erb
Информация о мероприятии <br><br>

<td><%= "Имя:" %> <%= @about_event.name %></td> <br>
<td><%= "Описание:" %> <%= @about_event.description %></td><br><br>
<td><%= "Город:" %> <%= @about_event.city %></td> <br>
<td><%= "Местоположение:" %> <%= @about_event.location %></td> <br>
<td><%= "Время:" %> <%= @about_event.date_and_time %></td> <br>
<td><%= "Картинка:" %> <%= image_tag @about_event.avatar.url(:thumb) %></td> <br>
<td><%= "ссылка:" %> <%= link_to @about_event.external_link, "http://#{@about_event.external_link}" %></td> <br>
<td><%= "Организатор:" %> <%= link_to @about_event.organizer.name, about_organizer_path(@about_event_organizer_id) %></td> <br>
<td><%= "Регион:" %> <%= @about_event.region.name %></td> <br><br>

<%= link_to 'CALENDAR URL', about_event_ics_file_url(protocol: :webcal, format: :ics) %> <br>
<%= link_to 'CALENDAR ICS DOWNLOAD', about_event_ics_file_path(protocol: :webcal, format: :ics) %>

app/views/mains/about_organizer.html.erb
Информация о организаторе <br><br>

<td><%= "Имя:" %> <%= @about_organizer.name %></td> <br>
<td><%= "Описание:" %> <%= @about_organizer.description %></td><br><br>
<td><%= "Cписок проведённых мероприятий" %></td> <br>
<td><% @sort_past_events.each do |event| %></td>
  <%= link_to event.name, about_event_path(event.id) %>
<% end %>

app/views/mains/all_events.html.erb
Список мероприятий <br>

<div><%= link_to 'Прошедшие мероприятия', show_past_events_path %></div>

<% @all_future_events.each do |event| %>
  <table>
    <tr>
      <td>Мероприятие: <%= link_to event.name, about_event_path(event) %></td>
      <td><%= event.description %></td><br>
<% end %>
</tr>
</table>
<%= will_paginate @all_future_events %>

app/views/mains/all_future_events.html.erb
Список мероприятий <br>

<div><%= link_to 'Прошедшие мероприятия', show_past_events_path %></div>

<% @all_future_events.each do |event| %>
  <table>
    <tr>
      <td>Мероприятие: <%= link_to event.name, about_event_path(event) %></td>
      <td><%= event.description %></td><br>
<% end %>
</tr>
</table>
<%= will_paginate @all_future_events %>

app/views/mains/all_organizers.erb
Список организаторов <br>

<% @all_organizers.each do |organizer| %>
  <table>
    <tr>
      <td><%= link_to organizer.name, about_organizer_path(organizer) %></td>
      <td><%= organizer.description %></td><br>
      <% end %>
    </tr>
</table>

app/views/mains/show_past_events.html.erb
Список прошедших мероприятий <br>
<% @past_events.each do |event| %>
  <table>
    <tr>
      <td>Мероприятие: <%= link_to event.name, about_event_path(event) %></td>
      <td><%= event.description %></td><br>
<% end %>
</tr>
</table>
<%= will_paginate @past_events %>